SP500-v0:
  num_envs: 4
  num_tasks: 20
  num_steps: 250
  n_adapt_steps: 1
  n_eval_episodes: 5
  total_timesteps: 2_000_000
  num_minibatches: 32
  save_freq: 5
  gamma: 0.99
  gae_lambda: 0.95
  outer_lr: !!float 3e-4
  inner_lr: !!float 3e-3
  clip_coef: 0.2
  clip_range_vf: 0.2
  vf_coef: 0.5
  ent_coef: 0.01
  max_grad_norm: 10
  normalize_advantage: True
  target_kl: null
  run_name: 'sp500'
  hiddens: [200, 200, 200, 100, 50]

VNALL-v0:
  num_envs: 4
  num_tasks: 10
  num_steps: 250
  n_adapt_steps: 1
  n_eval_episodes: 20
  total_timesteps: 20000
  num_minibatches: 32
  save_freq: 5
  gamma: 0.99
  gae_lambda: 0.95
  outer_lr: !!float 3e-4
  inner_lr: !!float 3e-3
  clip_coef: 0.2
  clip_range_vf: 0.2
  vf_coef: 0.5
  ent_coef: 0.01
  max_grad_norm: 10
  normalize_advantage: True
  target_kl: null
  run_name: 'vnall'
  hiddens: [200, 200, 200, 100, 50]

MiniFAANG-v0:
  num_envs: 2
  num_tasks: 2
  num_steps: 50
  n_adapt_steps: 1
  n_eval_episodes: 5
  total_timesteps: 20000
  num_minibatches: 32
  save_freq: 5
  gamma: 0.99
  gae_lambda: 0.95
  outer_lr: !!float 3e-4
  inner_lr: !!float 3e-3
  clip_coef: 0.2
  clip_range_vf: 0.2
  vf_coef: 0.19
  ent_coef: 0.02
  max_grad_norm: 5
  normalize_advantage: True
  target_kl: null
  run_name: null
  hiddens: [4, 4]

MiniVNStock-v0:
  num_envs: 2
  num_tasks: 2
  num_steps: 50
  n_adapt_steps: 1
  n_eval_episodes: 5
  total_timesteps: 20000
  num_minibatches: 32
  save_freq: 5
  gamma: 0.99
  gae_lambda: 0.95
  outer_lr: !!float 3e-4
  inner_lr: !!float 3e-3
  clip_coef: 0.2
  clip_range_vf: 0.2
  vf_coef: 0.5
  ent_coef: 0.01
  max_grad_norm: 10
  normalize_advantage: True
  target_kl: null
  run_name: null
  hiddens: [4, 4]