common-variables: &common-variables
  gamma: 0.99
  gae_lambda: 0.95
  clip_coef: 0.2
  clip_range_vf: 0.2
  vf_coef: 0.5
  ent_coef: 0.01
  max_grad_norm: 2
  max_loss: 5
  normalize_advantage: True
  target_kl: null
  is_timeout: True

SP500-v0:
  num_envs: 4
  num_tasks: 10
  num_steps: 250
  epochs: 200
  n_eval_episodes: 1
  minibatch_size: 500
  run_name: 'sp500'
  seed: null
  <<: *common-variables
  # mamlpp params
  inner_steps: 3
  msl_epoch: 20 # multi step loss
  meta_lr: !!float 7e-5
  min_lr: !!float 1e-6
  inner_optim_kwargs:
    lr: !!float 1e-4
    momentum: 0.9
  hiddens:
    - 1024
    - 512
    - pi: [256, 256]
    - vf: [256, 256]
  explore_kwargs:
    start: 1
    end: 0.1
    end_fraction: 0.3

# test env
VNALL-v0:
  num_envs: 5
  num_tasks: 5
  num_steps: 250
  epochs: 5
  n_eval_episodes: 20
  minibatch_size: 64
  hiddens: [200, 200, 200, 100, 50]
  run_name: 'vnall'
  seed: null
  <<: *common-variables
  inner_optim_kwargs:
    lr: !!float 7e-5
    momentum: 0.9

MiniFAANG-v0:
  num_envs: 5
  num_tasks: 5
  num_steps: 50
  epochs: 10
  n_eval_episodes: 1
  minibatch_size: 64
  meta_lr: !!float 1e-2
  hiddens: [16, 16]
  run_name: 'miniFAANG'
  seed: null
  <<: *common-variables
  # mamlpp params
  inner_steps: 3
  msl_epoch: 2 # multi step loss
  min_lr: !!float 1e-3
  inner_optim_kwargs:
    lr: 0.1
    momentum: 0.9
  test_optim_kwargs:
    lr: !!float 1e-3
    momentum: 0.9

MiniVNStock-v0:
  num_envs: 2
  num_tasks: 3
  num_steps: 50
  epochs: 5
  n_eval_episodes: 1
  minibatch_size: 64
  meta_lr: !!float 0.1
  hiddens: [4, 4]
  run_name: 'ministock'
  seed: null
  <<: *common-variables
  # mamlpp params
  inner_steps: 3
  msl_epoch: 2 # multi step loss
  min_lr: !!float 1e-2
  inner_optim_kwargs:
    lr: 0.1
    momentum: 0.9
  test_optim_kwargs:
    lr: !!float 1e-2
    momentum: 0.9