MountainCarContinuous-v0:
  num_envs: 1
  num_steps: 2048
  total_timesteps: 100000
  n_eval_episodes: 5
  num_minibatches: 32
  gradient_steps: 10
  gamma: 0.99
  gae_lambda: 0.95
  learning_rate: !!float 3e-4
  is_timeout: False
  clip_coef: 0.2
  clip_range_vf: 0.2
  vf_coef: 0.5
  ent_coef: 0.1
  max_grad_norm: 10
  normalize_advantage: True
  target_kl: null
  run_name: 'car'
  hiddens: [64, 64]

HalfCheetahDir-v0:
  num_envs: 4
  num_steps: 200
  total_timesteps: 100000
  n_eval_episodes: 5
  num_minibatches: 32
  gradient_steps: 10
  gamma: 0.99
  gae_lambda: 0.95
  learning_rate: !!float 3e-4
  is_timeout: False
  clip_coef: 0.2
  clip_range_vf: 0.2
  vf_coef: 0.5
  ent_coef: 0.01
  max_grad_norm: 10
  normalize_advantage: True
  target_kl: null
  run_name: 'halfcheetah'
  hiddens: [64, 64]