common-variables: &common-variables
  gamma: 0.9999
  gae_lambda: 0.9995
  clip_coef: 0.2
  clip_range_vf: null
  vf_coef: 0.5
  ent_coef: 0.02
  max_grad_norm: 5
  normalize_advantage: True
  target_kl: null

MountainCarContinuous-v0:
  num_envs: 5
  num_steps: 512
  total_timesteps: 50000
  n_eval_episodes: 5
  minibatch_size: 64
  gradient_steps: 3
  learning_rate: !!float 1e-3
  is_timeout: False
  evaluate_freq: null
  run_name: 'car'
  log_folder: 'log'
  model_folder: 'model'
  hiddens:
    - 32
    - pi: [32, 32]
    - vf: [32, 32]
  explore_kwargs:
    start: 0
    end: 0
    end_fraction: 0
  <<: *common-variables

HalfCheetahDir-v0:
  num_envs: 4
  num_steps: 100
  total_timesteps: 100000
  n_eval_episodes: 5
  minibatch_size: 64
  gradient_steps: 3
  learning_rate: !!float 3e-4
  is_timeout: False
  evaluate_freq: null
  run_name: 'halfcheetah'
  hiddens: [64, 64]
  <<: *common-variables

SP500-v0:
  num_envs: 10
  num_steps: 250
  total_timesteps: 1000000
  n_eval_episodes: 20
  minibatch_size: 64
  gradient_steps: 3
  learning_rate: !!float 3e-4
  is_timeout: True
  evaluate_freq: 5
  run_name: 'AAPL'
  task: 'AAPL'
  hiddens: [200, 200, 200, 100, 50]
  <<: *common-variables

# VNALL-v0:
#   num_envs: 4
#   num_steps: 250
#   total_timesteps: 20000
#   n_eval_episodes: 10
#   minibatch_size: 500
#   gradient_steps: 3
#   learning_rate: !!float 1e-4
#   is_timeout: True
#   evaluate_freq: 10
#   run_name: 'ppo_SSI'
#   log_folder: 'log/evaluation_M'
#   model_folder: 'model/evaluation_M'
#   task: 'SSI'
#   hiddens:
#     - 1024
#     - 512
#     - pi: [256, 256]
#     - vf: [256, 256]
#   explore_kwargs:
#     start: 1
#     end: 0.1
#     end_fraction: 0.3
#   <<: *common-variables

VNALL-v0:
  num_envs: 4
  num_steps: 250
  total_timesteps: 20000
  n_eval_episodes: 10
  minibatch_size: 500
  gradient_steps: 3
  learning_rate: !!float 1e-4
  is_timeout: True
  evaluate_freq: 2
  run_name: 'ppo_SSI'
  log_folder: 'log/evaluation_explore'
  model_folder: 'model'
  task: 'SSI'
  hiddens:
    - 1024
    - 512
    - pi: [256, 256]
    - vf: [256, 256]
  explore_kwargs:
    start: 1
    end: 0.01
    end_fraction: 0.2
  <<: *common-variables